/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.HospitalAdminWorkArea;

import System.EcoSystem;

import javax.swing.JPanel;
import System.Hospital.Hospital;
import System.Hospital.HospitalDirectory;
import System.Hospital.Patient.Patient;
import System.Hospital.Patient.PatientDirectory;
import System.Hospital.Staff.Staff;
import System.Hospital.Staff.StaffDirectory;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JSplitPane;

/**
 *
 * @author sanjeev
 */
public class CreatePatientdetails extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientdetails
     */
    private EcoSystem system;
    private JSplitPane jSplitPane1;

    JPanel managepatient;
    String Username;
    int id;
    public CreatePatientdetails(JSplitPane jSplitPane1,EcoSystem system,JPanel managepatient,String Username,int id) {
        initComponents();
         this.jSplitPane1 = jSplitPane1;
        this.system = system;
        this.Username = Username;
        this.id = id;
        
        populateFeild(system,Username,id);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHealthID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPatientname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPatientaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPatientCno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPatientmailID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtECname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtECno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPatientcity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPatientstate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPatientZipcode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtPatientage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPatientgender = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MANAGE PATIENTS:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 110, 310, 28));

        jLabel2.setText("Health ID ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 183, 123, 25));
        add(txtHealthID, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 183, 219, 25));

        jLabel3.setText("Patient ID ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 219, 123, 25));
        add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 219, 219, 25));

        jLabel4.setText("Name ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 262, 123, 25));
        add(txtPatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 262, 219, 25));

        jLabel5.setText("Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 367, 123, 25));
        add(txtPatientaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 367, 219, 25));

        jLabel6.setText("Contact No. ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 539, 123, 25));

        txtPatientCno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientCnoActionPerformed(evt);
            }
        });
        add(txtPatientCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 539, 219, 25));

        jLabel7.setText("mail ID ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 582, 123, 25));
        add(txtPatientmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 582, 219, 25));

        jLabel8.setText("Emergency Contact Name ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 625, 123, 25));
        add(txtECname, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 625, 219, 25));

        jLabel9.setText("Emergency Contact No.  ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 668, 123, 25));
        add(txtECno, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 668, 219, 25));

        jLabel10.setText("City");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 410, 123, 25));

        txtPatientcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientcityActionPerformed(evt);
            }
        });
        add(txtPatientcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 410, 219, 25));

        jLabel11.setText("State ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 453, 123, 25));

        txtPatientstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientstateActionPerformed(evt);
            }
        });
        add(txtPatientstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 453, 219, 25));

        jLabel12.setText("Zip Code");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 496, 123, 25));
        add(txtPatientZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 496, 219, 25));

        jLabel13.setText("Entry Date ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 725, 123, 26));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 792, -1, -1));

        jLabel14.setText("Age ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 298, 123, 25));
        add(txtPatientage, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 298, 219, 25));

        jLabel15.setText("Gender");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 331, 123, 25));
        add(txtPatientgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 331, 219, 25));

        jButton1.setText("Update");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 792, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 29, 40, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pr1.png"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 220, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientCnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientCnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientCnoActionPerformed

    private void txtPatientcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientcityActionPerformed

    private void txtPatientstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientstateActionPerformed


    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:

        jSplitPane1.setRightComponent(managepatient);
    }//GEN-LAST:event_jLabel16MouseClicked
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            HospitalDirectory hosDirectory;
            hosDirectory = system.getDBHospitalDirectory();
            for(Hospital h: hosDirectory.getHospitalDirectory())
            {
                if(h.getUserName().equals(Username))
                {
                    Patient pat = new Patient();
                    pat = h.addPatient();
                    pat.setHealthID(Integer.parseInt(txtHealthID.getText()));
                    pat.setPatientID(Integer.parseInt(txtPatientID.getText()));
                    pat.setName(txtPatientname.getText());
                    pat.setAge(Integer.parseInt(txtPatientage.getText()));
                    pat.setGender(txtPatientgender.getText());
                    pat.setAddress(txtPatientaddress.getText());
                    pat.setCity(txtPatientcity.getText());
                    pat.setState(txtPatientstate.getText());
                    pat.setZipcode(Integer.parseInt(txtPatientZipcode.getText()));
                    pat.setConNumber(Long.parseLong(txtPatientCno.getText()));
                    pat.setEmailID(txtPatientmailID.getText());
                    pat.setEmerConName(txtECname.getText());
                    pat.setEmerConNumber(Long.parseLong(txtECno.getText()));
                    pat.setHospitalUsername(Username);
                    
                    try {
                        system.savePatientDB(pat);
                    } catch (SQLException ex) {
                        Logger.getLogger(ManageStaffdetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    txtHealthID.setText("");
                    txtPatientID.setText("");
                    txtPatientname.setText("");
                    txtPatientage.setText("");
                    txtPatientgender.setText("");
                    txtPatientaddress.setText("");
                    txtPatientcity.setText("");
                    txtPatientstate.setText("");
                    txtPatientZipcode.setText("");
                    txtPatientCno.setText("");
                    txtPatientmailID.setText("");
                    txtECname.setText("");
                    txtECno.setText("");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageStaffdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtECname;
    private javax.swing.JTextField txtECno;
    private javax.swing.JTextField txtHealthID;
    private javax.swing.JTextField txtPatientCno;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientZipcode;
    private javax.swing.JTextField txtPatientaddress;
    private javax.swing.JTextField txtPatientage;
    private javax.swing.JTextField txtPatientcity;
    private javax.swing.JTextField txtPatientgender;
    private javax.swing.JTextField txtPatientmailID;
    private javax.swing.JTextField txtPatientname;
    private javax.swing.JTextField txtPatientstate;
    // End of variables declaration//GEN-END:variables

    private void populateFeild(EcoSystem system, String Username, int id) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       if(id!=-1)
      {
          try {
            // TODO add your handling code here:
            PatientDirectory patDirectory;
            patDirectory = system.getDBPatientDirectory();
            for(Patient p: patDirectory.getPatientDirectory())
            {
                if(p.getPatientID()==id)
                {
                    txtHealthID.setText(String.valueOf(p.getHealthID()));
                    txtPatientID.setText(String.valueOf(p.getPatientID()));
                    txtPatientname.setText(p.getName());
                    txtPatientage.setText(String.valueOf(p.getAge()));
                    txtPatientgender.setText(p.getGender());
                    txtPatientaddress.setText(p.getAddress());
                    txtPatientcity.setText(p.getCity());
                    txtPatientstate.setText(p.getState());
                    txtPatientZipcode.setText(String.valueOf(p.getZipcode()));
                    txtPatientCno.setText(String.valueOf(p.getConNumber()));
                    txtPatientmailID.setText(p.getEmailID());
                    txtECname.setText(p.getEmerConName());
                    txtECno.setText(String.valueOf(p.getEmerConNumber()));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageStaffdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }
}
