/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.HospitalAdminWorkArea;

import System.EcoSystem;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Subhash
 */
public class HospitalAdministrationArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdministrationArea
     */
    private EcoSystem system;
    private JSplitPane jSplitPane1;
    private String Username;
    JPanel jPanel2;
    JPanel Managepanel;
    public HospitalAdministrationArea(JSplitPane jSplitPane1,EcoSystem system, String Username,JPanel jPanel2,JPanel Managepanel) {
        initComponents();
        this.jSplitPane1 = jSplitPane1;
        this.system = system;
        this.Username = Username;
        this.jPanel2=jPanel2;
        this.Managepanel=Managepanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hospitalmain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManagePatient = new javax.swing.JButton();
        btnManagestaff = new javax.swing.JButton();
        btnLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Hospitalmain.setBackground(new java.awt.Color(255, 255, 255));
        Hospitalmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel1.setText("WELCOME !!!");
        Hospitalmain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 440, 41));

        btnManagePatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManagePatient.setText("Manage Patient");
        btnManagePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientActionPerformed(evt);
            }
        });
        Hospitalmain.add(btnManagePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, -1, -1));

        btnManagestaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManagestaff.setText("Manage Staff");
        btnManagestaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagestaffActionPerformed(evt);
            }
        });
        Hospitalmain.add(btnManagestaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-shutdown-40.png"))); // NOI18N
        btnLogout.setText("jLabel3");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        Hospitalmain.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hospital logo.png"))); // NOI18N
        Hospitalmain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hospitalmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hospitalmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientActionPerformed
        // TODO add your handling code here:
        ManagePatient mp = new ManagePatient(jSplitPane1,system,Managepanel,Username,-1);
        jSplitPane1.setRightComponent(mp);
    }//GEN-LAST:event_btnManagePatientActionPerformed

    private void btnManagestaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagestaffActionPerformed
        // TODO add your handling code here:
        ManageStaffdetails msd = new ManageStaffdetails(jSplitPane1,system,Username,-1,Hospitalmain);
        jSplitPane1.setRightComponent(msd);
    }//GEN-LAST:event_btnManagestaffActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:


        jSplitPane1.setRightComponent(jPanel2);
    }//GEN-LAST:event_btnLogoutMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hospitalmain;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnManagePatient;
    private javax.swing.JButton btnManagestaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
