/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.SysAdminWorkArea;


import System.EcoSystem;
import System.Registry.Registry;
import System.Registry.RegistryDirectory;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sanjeev
 */
public class ManageRegistry extends javax.swing.JPanel {

    /**
     * Creates new form ManageRegistry
     */
    private EcoSystem system;
    private JSplitPane jSplitPane1;
   
    Registry registry;
    RegistryDirectory registryDirectory;
    public ManageRegistry(JSplitPane jSplitPane1,EcoSystem system,RegistryDirectory registryDirectory) {
        initComponents();
        this.jSplitPane1 = jSplitPane1;
        this.system = system;
      this.registryDirectory = registryDirectory;
       

    

     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRegaddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRegstate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHospitalsearch = new javax.swing.JTextField();
        txtRegzipcode = new javax.swing.JTextField();
        txtRegcity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtRegpassword = new javax.swing.JTextField();
        txtReglogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRegname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistry = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        txtRegistrymail = new javax.swing.JTextField();

        btnView.setText("View ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel6.setText("City");

        jLabel5.setText("Address Line ");

        jLabel8.setText("Zip Code");

        jLabel3.setText("Login Name");

        btnSearch.setText("Search");

        jLabel4.setText("Password");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE REGISTRY SYSTEM");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel7.setText("State");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtReglogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegloginActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        tblRegistry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name ", "Login Name ", "Password", "Address Line", "City", "State", "Zip Code", "Mail ID "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegistry);

        jLabel19.setText("Mail ID ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(67, 67, 67)
                                    .addComponent(txtRegname, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtReglogin)
                                        .addComponent(txtRegpassword)
                                        .addComponent(txtRegaddress)
                                        .addComponent(txtRegcity)
                                        .addComponent(txtRegstate)
                                        .addComponent(txtRegzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(67, 67, 67)
                        .addComponent(txtRegistrymail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addGap(237, 237, 237)
                        .addComponent(btnUpdate)
                        .addGap(227, 227, 227)
                        .addComponent(btnDelete)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHospitalsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHospitalsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnDelete)
                                    .addComponent(btnView)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtRegname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtReglogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtRegpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtRegaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtRegcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtRegstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtRegzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtRegistrymail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnSave)))))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegloginActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        
         if (txtRegname.getText().isEmpty()) {
            txtRegname.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegname.setForeground(Color.red);

        }
        if (txtReglogin.getText().isEmpty()) {
            txtReglogin.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtReglogin.setForeground(Color.red);

        }
        if (txtRegpassword.getText().isEmpty()) {
            txtRegpassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegpassword.setForeground(Color.red);

        }
        if (txtRegistrymail.getText().isEmpty()) {
            txtRegistrymail.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegistrymail.setForeground(Color.red);

        }
        if (txtRegaddress.getText().isEmpty()) {
            txtRegaddress.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegaddress.setForeground(Color.red);
        }
        
          if (txtRegcity.getText().isEmpty()) {
            txtRegcity.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegcity.setForeground(Color.red);
        }
     
          if (txtRegstate.getText().isEmpty()) {
            txtRegstate.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegstate.setForeground(Color.red);
        }
          
          if (txtRegzipcode.getText().isEmpty()) {
            txtRegzipcode.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtRegzipcode.setForeground(Color.red);
        }
          
         //Null Value Check
         
         if (txtRegname.getText().isEmpty()
                || txtReglogin.getText().isEmpty()
                || txtRegpassword.getText().isEmpty()
                || txtRegistrymail.getText().isEmpty()
                || txtRegaddress.getText().isEmpty()
                || txtRegcity.getText().isEmpty()
                || txtRegzipcode.getText().isEmpty()
                || txtRegstate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter all fields");
        } 
         
         // Intitializing Registry Object
         
         Registry newreRegistry = registryDirectory.addRegistry();
         newreRegistry.setName(txtRegname.getText());
         newreRegistry.setUserName(txtReglogin.getText());
         newreRegistry.setPassword(txtRegpassword.getText());
         newreRegistry.setEmail(txtRegistrymail.getText());
         newreRegistry.setAddress(txtRegaddress.getText());
         newreRegistry.setCity(txtRegcity.getText());
         newreRegistry.setState(txtRegstate.getText());
         newreRegistry.setZipCode(Integer.parseInt(txtRegzipcode.getText()));
         
         JOptionPane.showMessageDialog(this, "New Registry is added!!");
         
         txtRegname.setText("");
         txtReglogin.setText("");
         txtRegpassword.setText("");
         txtRegistrymail.setText("");
         txtRegaddress.setText("");
         txtRegcity.setText("");
         txtRegstate.setText("");
         txtRegzipcode.setText("");
         
         
         
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:       
        
        int selectedRowIndex = tblRegistry.getSelectedRow();
        
        if(selectedRowIndex <0){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;            
        }
        
        DefaultTableModel model = (DefaultTableModel) tblRegistry.getModel();
        Registry selectedEntry = (Registry) model.getValueAt(selectedRowIndex, 0);       
        
         
        txtRegname.setText(selectedEntry.getName());
        txtReglogin.setText(selectedEntry.getUserName());
        txtRegpassword.setText(selectedEntry.getPassword());
        txtRegistrymail.setText(selectedEntry.getEmail());
        txtRegaddress.setText(selectedEntry.getAddress());
        txtRegcity.setText(selectedEntry.getCity());
        txtRegstate.setText(selectedEntry.getState());
        txtRegzipcode.setText(String.valueOf(selectedEntry.getZipCode()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        int selectedRowIndex = tblRegistry.getSelectedRow();
        
        if(selectedRowIndex <0){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;            
        }
        
        DefaultTableModel model = (DefaultTableModel) tblRegistry.getModel();
        Registry selectedEntry = (Registry) model.getValueAt(selectedRowIndex, 0);       
        
        
        String name = txtRegname.getText();
        String userName = txtReglogin.getText();
        String password = txtRegpassword.getText();
        String email = txtRegistrymail.getText();
        String address = txtRegaddress.getText();        
        String city = txtRegcity.getText();
        String state = txtRegstate.getText();
        int zipcode = Integer.parseInt(txtRegzipcode.getText());
          
          
          Registry registry = registryDirectory.searchRegistry(txtReglogin.getText());
          
          registry.setName(name);
          registry.setUserName(userName);
          registry.setPassword(password);
          registry.setEmail(email);
          registry.setAddress(address);
          registry.setCity(city);
          registry.setState(state);
          registry.setZipCode(zipcode);
          
          JOptionPane.showMessageDialog(this, "Registry is updated!!");
          
         txtRegname.setText("");
         txtReglogin.setText("");
         txtRegpassword.setText("");
         txtRegistrymail.setText("");
         txtRegaddress.setText("");
         txtRegcity.setText("");
         txtRegstate.setText("");
         txtRegzipcode.setText("");
          
          
          
                 
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
         Registry registry = registryDirectory.searchRegistry(txtReglogin.getText());
         
         registryDirectory.removeRegistry(registry);
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistry;
    private javax.swing.JTextField txtHospitalsearch;
    private javax.swing.JTextField txtRegaddress;
    private javax.swing.JTextField txtRegcity;
    private javax.swing.JTextField txtRegistrymail;
    private javax.swing.JTextField txtReglogin;
    private javax.swing.JTextField txtRegname;
    private javax.swing.JTextField txtRegpassword;
    private javax.swing.JTextField txtRegstate;
    private javax.swing.JTextField txtRegzipcode;
    // End of variables declaration//GEN-END:variables

 
    }




}
